### ISSUE TITLE
Status of getting the extension available on the Safari Extension store

### ISSUE THREAD

**Issue by simeg** [televator-apps/vimari#103]
I just enrolled into the Apple Developer Program and I will be looking into what changes need to happen to the code before sending it in for review.

I'll keep you updated in this issue!

----

**UPDATED**
Read the full issue for context.

TODO
- [ ] Settings
- [ ] Make it possible to open **multiple** links in new tabs
- [ ] Figure out how to distribute extension
- [ ] What website to open on new tab? Empty string doesn't work so we need something else, ideally the equivalent of `about:config` in other browsers

**Comment by simeg** [comment]
Read some docs from Apple and they are not great. It looks like the code needs to be wrapped in a macOS app, but it doesn't say of which type. I'll be busy for a few days now but will try to squeeze in some of this work.

If someone has experience with this or want to help out, please let me know.

**Comment by simeg** [comment]
Been messing around with it now for some time, and man.. the docs are killing me. I'm curious how they expect everyone to migrate their Safari Extensions to Safari App Extensions with this poor documentation that doesn't have any examples. It's gonna take a long time before all extensions are migrated :/

Anyway I got something up and running now, I can use the extension, kinda, but I need to understand the lifecycle of loading the extension before progressing any further. Also I haven't found any support for having settings for the extension which would suck if that was true.

Also I think we can get away with not having the extension on the App Store, but I'm not sure yet. I've read in some forums about it but haven't investigated more closely. That would mean we have instant releases, but with the downside that you have to come here to Github to download it - instead of opening up App Store. Will investigate this more further on.

**Comment by simeg** [comment]
I've gotten a version working with Safari 12 now. It's a very hacky solution but it works. However, the settings cannot be changed unless you change them in the code.

Follow the progress in my PR #104.

**Comment by LiYunyang** [comment]
I am testing on Mojave (18A326h) and could not build the project. It warns:

> **Code Signing Error:** No account for team "SK24TBMYCC". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
**Code Signing Error:** No signing certificate "Mac Development" found:  No "Mac Development" signing certificate matching team ID "SK24TBMYCC" with a private key was found.

**Comment by simeg** [comment]
@LiYunyang Did you try any of [these](https://stackoverflow.com/questions/47770693/xcode-wont-let-to-build-for-device-after-denying-codesign-to-access-keychain) [solutions](https://stackoverflow.com/questions/41205250/swift-sdtlib-tool-error-task-failed-with-exit-code-1)?

**Comment by simeg** [comment]
After spending some more time on this I'm not certain we'll be able to migrate all the features, not even some basic ones :(. The API is so limited unless you're working with a popover or toolbar. I don't understand why and I'm trying my best at finding information but since this is so new + Apple's awful documentation, there is none. Like opening a new tab is trivial from a popover/toolbar click but impossible otherwise. Apple will kill most of the current extensions with this approach. I will keep trying but can't promise anything.

**Comment by akrabat** [comment]
Thanks @simeg. I've successfully built it with my own developer certificate and it works with Safari 12 on macOS 10.13.6 High Sierra.,

**Comment by akrabat** [comment]
Yes. There was an error on build related to the certificates, so I selected mine in the drop-down.

**Comment by simeg** [comment]
After taking a few days break from this and getting some help I've managed to find some information that I think will make us able to migrate more features than I initially expected! So what's on my radar now:
* Migrating all the features
* Making sure it's possible to install the extension without having a developer certificate. If you have tried and failed it would be useful if you could post the error message(s) here, because right now I'm not sure how to fix this

**Comment by simeg** [comment]
[rant] [I am not the only frustrated developer](https://forums.developer.apple.com/thread/62410), it seems like. I did what the Apple staff person recommended, I filed a Bug Report where I for ask for an API with more functionality. It's grasping for straws but I don't know what else to do.. Hopefully Apple will realise that they are killing the extension ecosystem for Safari and change the API and write better documentation. [/rant]

Here are the features that are specified in the README:

f       Toggle links
F       Toggle links (open link in new tab)
k       Scroll up
j       Scroll down
h       Scroll left
l       Scroll right
u       Scroll up half page
d       Scroll down half page
g g     Go to top of page
G       Go to bottom of page

H       History back
L       History forward
r       Reload
~~w       Next tab~~
~~q       Previous tab~~
~~x       Close current tab and go to left tab~~
~~X       Close current tab and go to right tab~~
~~t       Open new tab~~

The lines with strikethrough will not work in Safari App Extensions with the current API, which sucks. However now that this work has been done I can focus on making vimari available for everyone, both via download and also in the future in the App Extension Store.

I'm sorry that many of you donated money towards getting 100% of the functionality available in Safari 12, but there's nothing I can do to change the API :( I hope you understand, and I am still dedicated to making this extension better.

**Comment by akrabat** [comment]
FWiW, The ones available are the key ones for me. Though I couldn't get `F` to work and had to remap it to `t`.

**Comment by simeg** [comment]
@akrabat Everything is not merged into master yet, so that is expected.

**Comment by simeg** [comment]
@LiYunyang I'm glad to hear it's working for you! Did you have to sign it with your developer account? Also, I have a PR open with some more features implemented that I haven't merged into master yet so if you check back in a few days you'll get more features. Like open link in new tab (`shift + t`) or open new empty tab (`t`). There are some minor problems related to them but I'm working on it.

**Comment by simeg** [comment]
I just merged my branch I've been working on into master which will enable two new features: open link in new tab (`shift + t`) and open new empty tab (`t`). It has a toolbar which doesn't do anything right now, I'm trying to figure out how to do settings so just ignore it for now.

**Comment by Rahlir** [comment]
So, it appears that one has to change the signing account in Xcode to compile - signing in with your Apple account in xcode and using that seems to work just fine.
I tried looking into making switching or closing tabs work. But @simeg is right - there is no support for that in the API right now and unless Apple adds it, I don't thing there is anything to do. Apple allows App extensions to access active tab, but doesn't allow to close it. They also don't allow access to all open tabs.

**Comment by simeg** [comment]
@Rahlir Yeah, I still have some minor issues like that to figure out. Not sure how to do it. I will publish this to the official app extension soon and hopefully that will get rid of those kind of issues. I am also confused to why Apple would do something like this. I think it will seriously lower the usage of Safari.

What I'm trying to figure out right now is settings. I can't find any info on what the recommended way is so I'm trying to see what other people did by looking at their code, but I'm progressing slowly. Will keep you updated.

**Comment by jdf221** [comment]
> What I'm trying to figure out right now is settings. I can't find any info on what the recommended way is so I'm trying to see what other people did by looking at their code, but I'm progressing slowly. Will keep you updated.

If you are talking about storing settings in your native Swift code the recommended way would be [UserDefaults](https://developer.apple.com/documentation/foundation/userdefaults).

https://www.hackingwithswift.com/read/12/2/reading-and-writing-basics-userdefaults

Obviously you'll have to have your saving/loading logic in Swift and then pass it down to your JS with an event. (something like "getSettings" "saveSettings" probably)

It's absolutely insane how much functionality they removed from extensions. If they actually want good extensions they will have to implement the WebExtensions standard otherwise barely anyone is going to convert/support their extensions for Safari.

**Comment by simeg** [comment]
@jdf221 Wow, you don't know how much I appreciate having someone to ask questions to - I really appreciate that. I wish I had the energy to work more on this at the moment. I'm facing some tough things in my personal life at the moment, but hopefully I'll find some motivation to get back on this project. I appreciate everyone's patience.

**Comment by Benhgift** [comment]
I just wanted to pop in and say that it would be amazing if it was on the app store.

I just spent a long time trying to get it to compile before succeeding thanks to this: https://stackoverflow.com/questions/39754341/none-of-your-accounts-are-a-member-code-signing-errors-after-upgrading-to-xcode

It was painful

**Comment by nchase** [comment]
@simeg can you share the publishing rights? I'm registered as an Apple Developer and I'd love to get this published and continue to help.

**Comment by nchase** [comment]
Hey folks, I spent some time this morning getting this to work and it has been submitted for verification. If all goes well, I expect that we'll see Vimari on the Mac App Store within a few days. I made a custom fork, incorporated a recent PR that includes a nice icon, etc.

BUT, I wanted to call out that there's another solution out there that already exists on the app store and seems to be WAY better maintained. **Please check out sVim: https://github.com/flipxfx/sVim**

If you just want to use a thing that works like Vimium, which is what I feel like is what 95% of people want, just download it from the Mac App Store here: https://safari-extensions.apple.com/details/?id=com.flipxfx.svim-6Q2K7JYUZ6

**Comment by nchase** [comment]
This got rejected from the App Store for the following reasons:

1. Doesn't work with MacOS's Dark Mode.
2. There is no content in the Window Menu of the extension – this is definitely real.

If anyone is very committed to Vimari, we'd need to fix these things before re-submitting if we had any hope of getting into the App Store to make it easier to download. But I'd strongly suggest checking out sVim, which is mentioned in my comment above as well: https://safari-extensions.apple.com/details/?id=com.flipxfx.svim-6Q2K7JYUZ6

**Comment by danielcompton** [comment]
@nchase, won’t that suffer the same fate as this extension with the next release of macOS? Isn’t the Safari Extension store going away, and the only way to get extensions is bundled in apps?

**Comment by nchase** [comment]
Ah. For some reason I thought it was already in the mac app store, sorry about that.

sVim seems a bit better maintained (someone is actively merging pull requests there as recently as a few months ago and the extension doesn't have either of the problems that got me rejected when I submitted Vimari, so it seems like the lift would be smaller to get it where it needs to be, but I could be wrong). 

Haven't looked into the code at all, really.

@danielcompton  Do you have any interest in being a champion of Vimari? (If you did, I could just push the changes I've made so far to my remote and you can pick up there.)

**Comment by danielcompton** [comment]
Yep I have thought about this and am running my own build locally which has merged a few PRs. I’ve also thought it would be good long term to get the Safari build based more closely on the upstream project so we can take advantage of (and contribute to) improvements in the original code base.

**Comment by nchase** [comment]
Awesome 😄

Do you have any perspective on sVim vs Vimari? (i.e. have you dug deep enough to have an opinion on the code and architecture of each?)

**Comment by danielcompton** [comment]
I wasn't aware of sVim until you mentioned it, but it also derives from a Chrome plugin: [cVim](https://chrome.google.com/webstore/detail/cvim/ihlenndgcmojhcghmfjfneahoeklbjjh) which has ~30k users. Vimari derives from [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb) which has ~300k users. I use Vimium in Chrome too.

cVim explains some [differences](https://github.com/1995eaton/chromium-vim#why-is-this-different-than-vimium-vichrome-or-vrome) though those are [five years old](https://github.com/1995eaton/chromium-vim/commit/62bd6c5c2304871c3de105c79c99340f2ff17fa4#diff-04c6e90faac2675aa89e2176d2eec7d8R11) and Vimium may have some or all of them now. None of the listed features have been that important for me, although I could see why people might want them.

I can't really make any more informed comparisons of them right now, what are your thoughts?

**Comment by nchase** [comment]
I use Vimium in Chrome too, which is how I found Vimari :) 

Depending on how easy it is to port features from Vimium, I'd say that's still my first choice since it's so vibrant and active.

A few years ago I was able to write up a pull request that got merged into Vimium without a lot of work (i.e. the code was pretty clear and easy to comprehend and alter, and glancing at Vimium again it still seems to be pretty small and comprehensible  – I guess it's written in coffeescript which is a minor barrier but worth mentioning).

At a distance it seems like it shouldn't be horrendous to port features/maintain parity 🤷‍♂️

I think the real work is going to be getting this project ready for the App Store

**Comment by simeg** [comment]
Hey everyone,

In January 2018 I committed to putting this extension on the App Store and people donated money towards that goal. I want to apologize to those of you who donated; I honestly thought I had the energy and perseverance to make it so but things happened that made my focus turn elsewhere. As I've mentioned before I had some upsets in my personal life that made me prioritising feeling OK again over anything else. I'm now feeling OK again 🙂 and if anyone wants their money back I will gladly return it. E-mail me at s.egersand@gmail.com for a refund! I feel bad for not completing what I promised and I don't want anyone to feel duped.

As for the project goes I will not continue this goal. I'm happy to see other people step up and if I can be of any support let me know. The owner of this project is not active anymore but I might be able to put you in contact with him for access to the repo.

**Comment by danielcompton** [comment]
> I'm happy to see other people step up and if I can be of any support let me know. The owner of this project is not active anymore but I might be able to put you in contact with him for access to the repo.

Thanks, I've sent an email to Guy about taking over maintenance of this project and getting it into the App Store. I'm hoping to get something in there by Catalina's release date so that upgraders have something to move to.

**Comment by guyht** [comment]
Hi all,

I plan to transfer Vimari over to @danielcompton .  I have opened a separate issue to discuss any last comments before the transfer - please post any comments in #137

**Comment by simeg** [comment]
Closed in favor of #139.
