### ISSUE TITLE
Open link in a background tab?

### ISSUE THREAD

**Issue by isundaylee** [televator-apps/vimari#114]
### Version

- [x] Version 1
- [ ] Version 2

### My Problem

In Safari 11.1.2, when I use Shift+F followed by the link hint to open a link in the new tab, the browser immediately switches to the new tab. Is there a way to open a link in a new background tab instead? 

Thanks! :)

**Comment by simeg** [comment]
Hi. [We're using `window.open()` for opening a tab](https://github.com/guyht/vimari/blob/master/vimari.safariextension/js/link-hints.js#L352), but the [Safari docs](https://developer.apple.com/documentation/safariextensions/safaribrowserwindow/1635509-opentab) say that if we use their `openTab()` we can decide on whether to open in background of foreground.

I agree that it should be configured, or just let background be default. Personally I think background feels more natural.

**Comment by akrabat** [comment]
I believe this is fixed with version 2.0.3. At least, `shift+f` works for me in Safari 13.0.1 on Mojave with Vimari 2.0.3..

**Comment by danielcompton** [comment]
Thanks @akrabat, I think you're right. Will close this for now.
