### ISSUE TITLE
Suggested change. settings.js: change 'F' to 'shift+f'

### ISSUE THREAD

**Issue by fnurl** [televator-apps/vimari#120]
**Suggestion to change keybinding from `'F'` to `'shift+F'`.**

In 158d54ed36c91cd304a2fab30621149060375761 `settings.js` has 

```
'newTabHintToggle': 'F',
```

which did not work for me (using macOS 10.13.6 (17G65), Safari 12.0 (13606.2.11)). Changing to

```
'newTabHintToggle': 'shift+f',
```

however does work. Am I experiencing a special case? Any reason why?

**Comment by simeg** [comment]
Hi @fnurl.

What version are you using? The commit you linked to is a PSD file, is that you what you intended?

I've not seen this before but depending on the version you're using it might be a bug.

**Comment by danielcompton** [comment]
I was able to verify this issue, and use your provided workaround. Thanks @fnurl!
