### ISSUE TITLE
Cannot install on Mojave

### ISSUE THREAD

**Issue by martinbohman** [televator-apps/vimari#121]
### Version

- [ ] Version 1
- [X] Version 2

### My Problem
Are there any more detailed installation instructions for Safari 12 and Mojave?
I assume I need a step by step setup of Xcode (v 10), since I don't use it otherwise.
In the build step, all I'm getting is this: 

>No account for team "SK24TBMYCC". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials. (in target 'vimari')

>No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "SK24TBMYCC" with a private key was found. (in target 'vimari')

**Comment by martinbohman** [comment]
Ok, I got a bit further. These are my steps for macOS 10.14 Mojave, Safari 12.0, Xcode 10.0

1. In Xcode Settings->Accounts, add your Apple ID if you don't have an account already. Create a Mac Development certificate.
2. In Xcode, press "vimari" at the top level of the file tree. You will then get settings in categories "Identity", "Signing" etc.
3. In Signing->Team, select your own identity.
4. At the top left of this settings menu, right above "Identity", it should say "vimari". Press this to get a dropdown with two options for "Targets". Select "extension" and select your own identity again in the Signing->Team dropdown.
5. Not sure if necessary but I changed some settings in extension/js/lib/settings.js and then in the right pane checked both "vimari" and "extension" in "Target Membership"
6. CMD-R will now successfully build the project. You will get a prompt to select what application to run, it seems like you can select whatever (I used TextEdit). The extension will now be running and waiting for Safari to open.
7. Open Safari. Open extensions menu and enable vimari. Verify that it is working.
8. Go back to Xcode, press stop button. Quit Xcode.
9. Vimari will still be working but it will have disappeared from the extensions menu.

**THE PROBLEM STILL**
Vimari won't stay working if I restart Safari. If I quit Safari I have to open the project in Xcode again, CMD-R, (select TextEdit or whatever), open Safari, then quit Xcode.

Hopefully this can be of help to someone, both for getting it to run and to debug/improve the installation process.

**Comment by simeg** [comment]
Hej @martinbohma, och tack!

I'm glad you figured out to make it work - I appreciate you sharing the steps with us! I've added some more info to the instructions (https://github.com/guyht/vimari/commit/3538260637449677b1d3dc6dfecca1a3f46a7d07), do you think the SO answer I referenced is enough to solve this problem? You probably have a better understanding than me.

I think the only way to make it stay in Safari is to put it on the App Store, which I will look into after managing to figure out how to change Settings.

**Comment by ZeerakW** [comment]
Hej!

I can't seem to make this process work. Specifically the difference first occurs in step 6, where on running the project, no prompt appears asking me to select an application. Subsequently the extension is not available in Safari. 

The setup is the same as Martin's.

**Comment by khang-11** [comment]
I found an easier way to install the extension. 
1. Go to Safari Preferences -> Advanced -> Show Develop menu in menu bar
2. From 1.13 release, download vimari.safariextension
3. On Safari, click Develop -> Show Extension Builder
4. Add the vimari.safariextension folder
5. Click run

**Comment by sdondley** [comment]
I was able to get it successfully installed in Mojave following special install instructions on GitHub.

**Comment by orthodoX** [comment]
@khang-11 thanks man, you saved me so much efforts, I was not able to build it from Xcode several times!

**Comment by FelipeCRamos** [comment]
> I found an easier way to install the extension.
> 
> 1. Go to Safari Preferences -> Advanced -> Show Develop menu in menu bar
> 2. From 1.13 release, download vimari.safariextension
> 3. On Safari, click Develop -> Show Extension Builder
> 4. Add the vimari.safariextension folder
> 5. Click run

Only method that worked out for me! Thanks!!

**Comment by tkb** [comment]
> I found an easier way to install the extension.
> 
> 1. Go to Safari Preferences -> Advanced -> Show Develop menu in menu bar
> 2. From 1.13 release, download vimari.safariextension
> 3. On Safari, click Develop -> Show Extension Builder
> 4. Add the vimari.safariextension folder
> 5. Click run

Thanks! This worked very well for me too. Safari 12.0.2 on OSX 10.14.2

**Comment by normenmueller** [comment]
> I found an easier way to install the extension.
>
> 1. Go to Safari Preferences -> Advanced -> Show Develop menu in menu bar
> 1. From 1.13 release, download vimari.safariextension
> 1. On Safari, click Develop -> Show Extension Builder
> 1. Add the vimari.safariextension folder
> 1. Click run

@khang-11 Do I have to repeat these steps every time I start Safari?

**Comment by normenmueller** [comment]
@orthodoX So, the answer to

> Do I have to repeat these steps every time I start Safari?

is: Yes ;-)

**Comment by BakerChan** [comment]
> I found an easier way to install the extension.
> 
> 1. Go to Safari Preferences -> Advanced -> Show Develop menu in menu bar
> 2. From 1.13 release, download vimari.safariextension
> 3. On Safari, click Develop -> Show Extension Builder
> 4. Add the vimari.safariextension folder
> 5. Click run

this works for me even in os Sierra with safari 12

**Comment by kwladyka** [comment]
https://github.com/guyht/vimari/issues/121#issuecomment-424274616
I did steps from here, but "build failed" when `cmd + r`.
I have signing filled correctly. I have Identity with "Application Category". But there is no extension to choose. I have "Utilities". There is no way to build it. I have no idea how to work with xcode, but I would like so much to use it in Safari.

But I have honest question: Does this project is maintenance anymore? I think not.

**Comment by michael-yx-wu** [comment]
@kwladyka try the steps here instead: https://github.com/guyht/vimari/issues/121#issuecomment-434114565.

Longterm, if we want a "legit" installation path through the extension gallery, someone will probably need to fork this repo.

**Comment by kwladyka** [comment]
@michael-yx-wu Thank you. It almost work. I want to have only `f` shortcut. I edited `settings` file with shortcuts, but it still run extension with default (all of them) shortcuts instead.

**Comment by jdf221** [comment]
Just an FYI but the “.safariextension” method/extension is deprecated by Apple and it’s not possible to upload these deprecated extensions to the Extensions Gallery.

So just know that eventually the extension will stop working.

There’s been some work done on the App Extension version (the new Safari extension API) of this and it half works. (But it seems like there’s some trouble installing it)

The main contributor here has mentioned that he has some stuff going on in his life right now and doesn’t have the time/want to work on this.

I think the main things that need to be implemented in the app extension version is a settings page and a few of the key combos. I’ll take a look and see if I’m up for implementing them when I get the chance. Shouldn’t be too hard but I haven’t looked at the code here in months.

**Comment by simeg** [comment]
Hi, read more about my current involvement for this project in #103 (I'm the lead maintainer atm).

@jdf221 Any help would be greatly appreciated, but not expected. Let me know if I can help with anything. I agree the settings page is what's really blocking us from releasing this onto the App Store.

**Comment by michael-yx-wu** [comment]
Cool, following along in #103. Realize it may be some time before we see it completed but current workaround are okay at the moment!

@kwladyka i have the setup you're trying to achieve running on my machine. instead of editing a settings file, what I do is:
- run the extension in the developer builder menu
- open Safari settings > extensions > vimari and edit the `link hint toggle` setting there instead

**Comment by danielcompton** [comment]
I think this should be resolved now with recent work + the release of [2.0.2](https://github.com/televator-apps/vimari/releases/tag/v2.0.2), and the [imminent arrival](https://github.com/televator-apps/vimari/issues/139) of Vimari on the Mac App Store. Please open a new issue if there are still things that aren't working for you.
