### ISSUE TITLE
After 7 days vimari disappears

### ISSUE THREAD

**Issue by SMILElikeJONNY** [televator-apps/vimari#125]
### Version

- [ ] Version 1
- [X ] Version 2

### My Problem
After 7 days vimari disappears from safari. The problem is you need a developer account for a unlimited duration of the certificates. Do you know how I can fix that with out paying 99€ for a developer account?

**Comment by danielcompton** [comment]
I have a free developer account and my built version of Vimari has been running fine for months. Have you signed in to a free developer account in Xcode?

**Comment by czhu** [comment]
I have the same issue. My vimari disappears after 7 days after following the instruction. 
I believe my account is a free developer account. But I cannot be sure. Apple doesn't seem to have the free program anymore.

**Comment by danielcompton** [comment]
You can use the prebuilt notarized binaries now with [v2.0.2](https://github.com/televator-apps/vimari/releases/tag/v2.0.2), and this will be on the Mac App Store very soon (#139).
