### ISSUE TITLE
[UPDATE] Moving Vimari to a new maintainer

### ISSUE THREAD

**Issue by guyht** [televator-apps/vimari#137]
Hi All,

I started Vimari because I wanted to build something both for myself and the community, and have really enjoyed working on this extension as well as seeing so many people contribute and be a part of the project.

As is so often the case with these projects, other commitments have caught up with me and I dont have the personal capacity to continue maintaining this project (the truth is I have not done much on this project for a while).  I am very humbled to see so many people care about this project, and continue to contribute in a number of ways.

I really want to see Vimari continue, and @danielcompton reached out to me recently offering to take over the project.  I have agreed to hand over the project to Daniel based on the following conditions:

* Vimari should remain free and open source 

* The code should remain available on Github

* All contributors over the years should be credited as developers of the software

I believe that this will be the best path for Vimari, and will enable to the project to continue with the strong community that has developed around it.

I will leave this issue up for 24 hours until I complete the transfer to provide a forum for any further comments.

Finally, I would like to personally thank everyone that has contributed to Vimari over the last few years.

Thanks!
Guy

**Comment by danielcompton** [comment]
Thanks Guy! Looking forward to getting a release out into the Mac App Store. My plan is to get this done before Catalina is released 🤞.
