### ISSUE TITLE
Getting Vimari on the Mac App Store

### ISSUE THREAD

**Issue by danielcompton** [televator-apps/vimari#139]
This is a tracking issue to keep people up to date with the status of getting Vimari on the Mac App Store.

Vimari is currently "Waiting for Review"

<img width="1161" alt="Screenshot of Safari (21-09-19, 11-43-50 PM)" src="https://user-images.githubusercontent.com/811954/65372855-b7b2db00-dcc9-11e9-8188-81d27da72a8f.png">

**Comment by danielcompton** [comment]
While I'm waiting for App Review, I've released [v2.0.2](https://github.com/televator-apps/vimari/releases/tag/v2.0.2) including a notarized binary. This is the same as the Mac App Store version. 

If you're game, download it, take it for a spin, and let me know if you run into any issues. There should be no security warnings you have to disable to get it to run.

**Comment by translit** [comment]
Thanks so much, Daniel!

Now if only you could add a shortcut for jumping to the fist text field on a page (```gi```, for example).

**Comment by danielcompton** [comment]
> Now if only you could add a shortcut for jumping to the fist text field on a page (gi, for example).

This looks like a Vimium feature, follow along with #140 for more on getting up to date with Vimium.

**Comment by rshaehnel** [comment]
In the early release 2.0.2 version I can't get the "open a link in a new tab"("F" key) to work. "open link in current tab"("f" key) works fine.

**Comment by danielcompton** [comment]
Thanks, this is fixed in https://github.com/televator-apps/vimari/commit/aa897499b33020a251f7840cf4665683e71618fa, but not released yet.

**Comment by Hultner** [comment]
My Safari just autoupdated to 13, was putting it of for as long as possible due to fear of losing vi-bindings. Used the release from the releases page, works like a charm.

Thanks for making this happen! 
Seeing someone take over a project as primary maintainer like this, handed down multiple times is what open source is all about!

**Comment by nchase** [comment]
I  second Hultner's enthusiastic statement of thanks. Thanks again, @danielcompton

**Comment by danielcompton** [comment]
Thanks @Hultner and @nchase 😃.

I'm still waiting in app review to get it onto the store. I contacted Apple Developer support and they said it was still pending review, but nothing was necessarily wrong with it.

**Comment by danielcompton** [comment]
I've just released [2.0.3](https://github.com/televator-apps/vimari/releases/tag/v2.0.3) while I'm waiting for App Review, as there are some handy fixes in there.

**Comment by eproxus** [comment]
Maybe a stupid question (couldn't find any info in the repo or README), but:

How do I change settings with this version? Like the hint keys used etc.?

**Comment by nchase** [comment]
@eproxus hasn't been implemented in the UI yet – right now you have to edit the key mappings manually and rebuild Vimari

**Comment by eproxus** [comment]
@nchase Ah, got it. Thanks 😊

**Comment by danielcompton** [comment]
Thanks @nchase! You can follow https://github.com/televator-apps/vimari/issues/142 @eproxus to get updates for custom settings.

**Comment by danielcompton** [comment]
I'm happy to say that Vimari is now available on the Mac App Store! You can download it at https://apps.apple.com/us/app/vimari/id1480933944?ls=1&mt=12 once it has propagated around the world (next 24 hours?). Thanks to everyone who has worked on Vimari to get it here, particularly @nchase, @simeg, and @guyht.

In the future, I plan to release updates via the Mac App Store. This is (hopefully) a more reliable method of updating the extension, and provides an easy and safe distribution method which should (?) work for everybody.

**Comment by jesse-c** [comment]
Working perfectly, thank you! Added a review.

**Comment by Hultner** [comment]
> I'm happy to say that Vimari is now available on the Mac App Store! You can download it at https://apps.apple.com/us/app/vimari/id1480933944?ls=1&mt=12 once it has propagated around the world (next 24 hours?). Thanks to everyone who has worked on Vimari to get it here, particularly @nchase, @simeg, and @guyht.
> 
> In the future, I plan to release updates via the Mac App Store. This is (hopefully) a more reliable method of updating the extension, and provides an easy and safe distribution method which should (?) work for everybody. Sparkle updating might be tricky as the app itself doesn’t run very often, only the extension. It might be possible to check for updates from within the extension but that is probably unexpected, and a pain to deal with.
> 
> If you like Vimari, be sure to rate it on the App Store so others can find it.

Installed and reviewed, 5 stars and a thankful comment :)

**Comment by simeg** [comment]
Awesome job @danielcompton! 🎉🎉

**Comment by dvcrn** [comment]
I'm a big fan of vimari and wanted to say huge thanks for putting this up in the appstore! 🎉

**Comment by devnall** [comment]
Safari 13 is usable! Thanks to all who have contributed to getting this working and through the review process! MAS review left and looking forward to new features being implemented.
