### ISSUE TITLE
preference doesnt show up . 

### ISSUE THREAD

**Issue by Akatsuki-Ryu** [televator-apps/vimari#141]
### Version

- [ ] Version 1
- [x ] Version 2

### My Problem

i am running mac os x 10.14.6
safari 13.0 (14608.1.49)

i installed 2.0.2 vimari and the key binding and such settings doesnt show up in my preference menu in plugin list . 

i am attaching the screen shot here . 

please check , thank you very much 
<img width="475" alt="Screenshot 2019-09-23 at 17 31 05" src="https://user-images.githubusercontent.com/8062209/65434831-26a64600-de28-11e9-976e-f9e14b780ee4.png">
<img width="845" alt="Screenshot 2019-09-23 at 17 31 25" src="https://user-images.githubusercontent.com/8062209/65434874-39b91600-de28-11e9-81d9-d6de7f2932e7.png">

**Comment by danielcompton** [comment]
Hi @Akatsuki-Ryu. My first priority is getting _something_ on the Mac App Store as people are currently losing access to Vimari when they upgrade to Safari 13. In a later release I plan to look at settings. You can follow #142 for more on this. Thanks!

**Comment by Akatsuki-Ryu** [comment]
thank you very much for the info !
