### ISSUE TITLE
Navigation and new tab issue in 2.0.2

### ISSUE THREAD

**Issue by orthodoX** [televator-apps/vimari#143]
### Version

- [ ] Version 1
- [x ] Version 2

### My Problem

First of all thanks a lot for the 2.0.2 release! Finally we can use this great extension on Catalina! 🎉 

Found some issues though:
- The navigation between the tabs with **q** and **w** is not working.
- The new tab link open with **F** is not working. It won't even show the shortcut letters like regular **f** does

All others features are fine, though. I'm using **Safari 13.0.1 (15608.2.11.1.1)** on **Catalina 10.15 Beta (19A558d)**

**Comment by danielcompton** [comment]
Thanks, these are fixed on master, but not in a release yet.

**Comment by danielcompton** [comment]
I've released these fixes in https://github.com/televator-apps/vimari/releases/tag/v2.0.3.

**Comment by orthodoX** [comment]
@danielcompton Awesome! Thanks so much! 😍  I'll recheck the new version if it has any bugs.
