### ISSUE TITLE
Disable Youtube shortcut key for "f"

### ISSUE THREAD

**Issue by toilahung** [televator-apps/vimari#148]
**Is your feature request related to a problem? Please describe.**
After installing Vimium when I press "f" when visiting Youtube it would also trigger the youtube shortcut which will make the video fullscreen. That is very annoying.

**Describe the solution you'd like**
It would be great if Vimium disables youtube shortcut for "f".

**Describe alternatives you've considered**
An alternative that will work for other websites too is that Vimium should include the feature which enables us to customize its shortcuts then I could map Vimium shortcut to another key.

Thank you, Hung

**Comment by tbrodbeck** [comment]
+1000

**Comment by nbelzer** [comment]
This issue should be resolved in #176.
