### ISSUE TITLE
F does not work to open in new tab

### ISSUE THREAD

**Issue by eproxus** [televator-apps/vimari#149]
**Describe the bug**
Triggering link hints with <kbd>Shift</kbd>+<kbd>f</kbd> does not open links at all.

**To Reproduce**
1. Install latest Vimari release 2.0.3 in Safari Version 13.0.1 (14608.2.11.1.11)
2. Press <kbd>Shift</kbd>+<kbd>f</kbd> on any web page
3. Enter keys for a link hint
4. Nothing happens

**Expected behavior**
Link for pressed link hint should have been opened in a new tab.

**Desktop (please complete the following information):**

- macOS version: 10.14.6
- Safari version: 13.0.1
- Vimari version: 2.0.3

**Additional context**

Possible duplicate of #96 but since version 2.0.3 was created 5 days ago I assume the fix from `master` is included already.

**Comment by danielcompton** [comment]
Can you try restarting Safari? I can't reproduce this?

**Comment by eproxus** [comment]
Restarting Safari worked. But it happened again today. Anything I can do to debug it?

**Comment by danielcompton** [comment]
When you click "Show in Finder", what file path do you see? Do you have multiple copies of Vimari.app on your system?

<img width="424" alt="Screenshot of Safari (1-10-19, 11-40-25 PM)" src="https://user-images.githubusercontent.com/811954/65955547-e3da1300-e4a4-11e9-9bfd-4b6183a57a64.png">

**Comment by eproxus** [comment]
It's in `/Applications/Vimari.app` but I did run it from `~/Downloads` before I moved it into the Applications folder.

**Comment by danielcompton** [comment]
And there's only one copy on your system? Try emptying the Trash too (crazy I know, but I think this does have an impact on some bundle resolution logic).

**Comment by eproxus** [comment]
Only one, and trash is already empty.

**Comment by danielcompton** [comment]
I’m a bit stumped here, not really sure. Hopefully this issue goes away once the app is on the App Store. Reading between the lines, it seems like App Store apps have slightly different extension detection behaviour which may be less buggy. 🤷‍♂️

**Comment by eproxus** [comment]
Let's hope! Closing for now...
