### ISSUE TITLE
Make Vimari work on a new Safari tab which contains favourites links

### ISSUE THREAD

**Issue by VKondakoff** [televator-apps/vimari#152]
I set Safari preferences to create new tabs, which contains Favourites links. After opening new tab, I was hoping, that Vimary will work on this tab as on any other web page, but unfortunately, this is not true. Can you, please, make Vimari work on anew Safari tab which contains favourites links?
Thank you!

- macOS version: 10.15
- Safari version: 13.0.2
- Vimari version: 2.0.3

**Comment by danielcompton** [comment]
Unfortunately there is no API for this, closing in favour of #151.

**Comment by VKondakoff** [comment]
Thanks for looking into this.
Just a quick tip for hotkey-oriented people: you can use Alt-Ctrl-1...9 hotkeys to access the first nine of the links in your Favorites.
