### ISSUE TITLE
Excluded URLs

### ISSUE THREAD

**Issue by jonchoi** [televator-apps/vimari#153]
No settings access to excluded URLs? Is this a known issue?

**Desktop (please complete the following information):**
 - macOS version: 10.14.6 Mojave
 - Safari version: 13.0.1
 - Vimari version: Latest

**Comment by cloin** [comment]
I'm not able to find the settings page for Vimari.

**Comment by analyticd** [comment]
Same here on High Sierra and Safari 13.0.2

**Comment by danielcompton** [comment]
This is a known issue, there is no settings page yet in the new version of Vimari. My main focus so far has been getting it on the App Store. Now that it's there I'm going to look more at features like this.

**Comment by cloin** [comment]
@danielcompton understood. Respectfully, this application is quite ineffective without resolving this. If you aren't able to disable Vimari on certain pages, you're not able to use web app specific keyboard shortcuts. I'm looking forward to re-enabling this extension when this bug is resolved.

**Comment by namolnad** [comment]
@cloin @jonchoi FWIW, if you need to edit this prior to these improvements being merged in, looks like you can do so here: `/Applications/Vimari.app/Contents/PlugIns/Vimari Extension.appex/Contents/Resources/settings.js`. Just worked for me.

**Comment by namolnad** [comment]
I take this back, after a Safari restart it appears the extension will no longer load until the file is put back to its original state. Seems likely due to code signing
