### ISSUE TITLE
Vimari not working Safari 13.0.3 macOS Catalina 10.15.1

### ISSUE THREAD

**Issue by bananowaZyrafa** [televator-apps/vimari#159]
I installed Vimari for the first time, followed the instructions (enabled extension in Safari) but I can see no keyboard shortcuts displayed. 
Is there a way to turn it on/off?

**Comment by danielcompton** [comment]
You can see the keyboard shortcuts in https://github.com/televator-apps/vimari/blob/master/Vimari%20Extension/js/settings.js until I add a user visible screen for keyboard shortcuts in #142.
