### ISSUE TITLE
Pressing `t` opens a localhost page then further `t` or `x` command stop working

### ISSUE THREAD

**Issue by manish-makwana** [televator-apps/vimari#160]
**Describe the bug**
Pressing `t`, which should open a new tab, instead opens a tab with `localhost` in the address bar. Pressing other keys like `x`, `q` etc fail to work and the tab must be closed using built-in commands (cmd-w etc).

**To Reproduce**
1. Press `t` from any webpage, such as the [vimari github page](https://github.com/televator-apps/vimari).
2. See localhost page open up.

**Expected behavior**
The standard Safari new tab page opens up as per the Safari settings. (In my case, a list of favourites.)

**Screenshots**

**Desktop (please complete the following information):**

- macOS version: 10.14.6
- Safari version: 13.0.3
- Vimari version: 2.0.3

**Additional context**
None.

**Comment by danielcompton** [comment]
Sorry about this, it is a limitation in the Safari extensions API. On an "Empty Page", a "Top Sites" page, a "Favourites" page, or a page which doesn't load like `localhost`, Vimari is not injected, and cannot provide any keyboard shortcuts.

<img width="375" alt="Screenshot of Safari (18-11-19, 2-52-24 PM)" src="https://user-images.githubusercontent.com/811954/69018874-3058be00-0a13-11ea-8f62-7f296d49fd34.png">

**Comment by manish-makwana** [comment]
I'd like to help with updating the documentation, maybe adding a "Known Limitations" section in the readme, is that cool? What's your preferred way for this - shall I fork the repo, update then submit a merge request?

**Comment by danielcompton** [comment]
Sure!

**Comment by Hultner** [comment]
@danielcompton Could we maybe change from localhost to `about:blank` as default start page?
The Vimari shortcuts still work on about:blank

**Comment by danielcompton** [comment]
Unfortunately, it's only possible to load an http or https link. `SFSafariWindow.openTab(with:makeActiveIfPossible:completionHandler:)` doesn't allow opening the URL `about:blank`.

**Comment by realimpat** [comment]
This is bothering me too -- was there a resolution to this issue? 

The vimium-chrome version lets you type `O` to enter a url or search term that opens into a new tab, all at once, which is what I'd really hope to accomplish. The second best thing would be to open a search engine as a homepage in a new tab.

Despite setting a homepage in the safari preferences, though, new tabs always open a broken 'localhost.' 

Am I doing something wrong? This thread references docs, but I don't see any on the Vimari hompege. 
<img width="463" alt="Screen Shot 2020-07-22 at 1 23 55 PM" src="https://user-images.githubusercontent.com/34801063/88208017-9b9c0500-cc1e-11ea-90aa-f309821b8af8.png">

**Comment by realimpat** [comment]
Looks like this was fixed. Just wanted to express gratitude here!
