### ISSUE TITLE
Scrolling with `j` after pressing `d` jumps the scroll position to where it was before pressing `d`

### ISSUE THREAD

**Issue by Jayphen** [televator-apps/vimari#168]
**Describe the bug**
I think the title probably covers it.

**To Reproduce**
1. View any page that overflows vertically, i.e. https://github.com/televator-apps/vimari
2. Press `d` once
3. Press `j` once
4. Note that after pressing `j`, the scroll position jumps *up* to where it was before pressing `d`.

**Expected behavior**
Scrolling should continue from where it was after pressing `d`.

**Screenshots**
Here is a gif of me pressing d, then f, then d, then f. Notice the scroll jumping up.

![CleanShot 2020-03-02 at 13 27 57](https://user-images.githubusercontent.com/329184/75676511-abc04180-5c89-11ea-962a-d62c05aa5f62.gif)

**Desktop (please complete the following information):**

- macOS version: 10.15.3
- Safari version: 13.0.5
- Vimari version: 2.0.3

**Comment by normen** [comment]
This is because the site you chose to test (github) supports `j/k` out of the box to scroll through the code. It doesn't happen on other sites.

**Comment by ataias** [comment]
> This is because the site you chose to test (github) supports `j/k` out of the box to scroll through the code. It doesn't happen on other sites.

Is it possible to disable `j/k` default github support and force vimari support? On Firefox, the Vixen plugin does that, which helps keeping the experience consistent.

**Comment by normen** [comment]
Not anymore apparently, see the other issues about the missing configuration panel.

**Comment by nbelzer** [comment]
This issue has been resolved in #176.
