### ISSUE TITLE
No built app available for latest release - v2.1.0

### ISSUE THREAD

**Issue by AdamBeddoe** [televator-apps/vimari#203]
Only the source code and not the built app is available on the latest release.

Would be great if someone could add this for those of us that aren't familiar about building from source and unable to download from the App Store!

**Comment by nbelzer** [comment]
@danielcompton could you add the binary to the release?

**Comment by danielcompton** [comment]
[Done](https://github.com/televator-apps/vimari/releases/tag/v2.1.0), sorry about this, I didn't realise people were running this outside of the App Store versions. I'll try and remember to keep the Releases up to date with the App Store releases. 

Are you able to share more about why you're not able to download from the App Store?

**Comment by AdamBeddoe** [comment]
The reason I can't download from the App Store is because it's prohibited by my company policy because of the Apple T&Cs.

I realise that this is quite a niche situation so appreciate you adding the binary, thanks very much!
