### ISSUE TITLE
Dim icon when the URL is being ignored

### ISSUE THREAD

**Issue by KwatME** [televator-apps/vimari#210]
<img width="148" alt="Screen Shot 2020-11-08 at 11 14 23 AM" src="https://user-images.githubusercontent.com/7741548/98482056-8f2ebe80-21b3-11eb-8969-430f55a07309.png">

**Comment by nikitavoloboev** [comment]
Curious why you even need an icon there? You can always activate Vimari from Spotlight/Alfred.

**Comment by KwatME** [comment]
Safari added it there. Safari adds extensions there I think. I try to use the default settings and not modify the menu bar. In the past release or in Vimium, the icon dims itself when the web page is being ignored.
