### ISSUE TITLE
Apple Silicon Release

### ISSUE THREAD

**Issue by zinozzino** [televator-apps/vimari#219]
**Is your feature request related to a problem? Please describe.**
- App Store release supports Intel architecture only. It seems working fine with Rosetta 2, but we know universal binary is better.

**Describe the solution you'd like**
Release universal binary.

**Additional context**
Vimari Apple Silicon Build on M1 Mac works fine with no code change.

**Comment by Harry1993** [comment]
Does anyone know how to build it with Xcode without an Apple developer account?
