### ISSUE TITLE
Website blacklist

### ISSUE THREAD

**Issue by sealvessel** [televator-apps/vimari#222]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when vimari blocks the use of certain keys or inhibits the functions of some websites which already have keyboard shortcuts

**Describe the solution you'd like**
Have a URL check which reads a text file config which contains a list of addresses such as google.com, or youtube.com. If it matches, then vimari will not load it's javascript on that specific page.

**Describe alternatives you've considered**
Have a toggle hotkey to disable vimari.

**Comment by ideamotor** [comment]
This is already included in the configuration file as "excludedURLS". I was surprised that you don't quote each Website separately, e.g.:

"excludedUrls": "127.0.0.1, docs.google.com, https://www.memeorandum.com",

**Comment by sealvessel** [comment]
I am literally blind... Thanks.
