### ISSUE TITLE
command/meta key as shortcut?

### ISSUE THREAD

**Issue by godbout** [televator-apps/vimari#224]
**Is your feature request related to a problem? Please describe.**
i'm trying to add cmd+shift+h and cmd+shift+l to go back and forward. i can't seem to make it work. Vimium handles cmd with the <m-*> key (meta/command key). 

**Describe the solution you'd like**
finding how to be able to use the cmd key in shortcuts

**Describe alternatives you've considered**
adding myself the shortcut system-wise

**Additional context**
i'm trying to achieve this so that i can match all the browser apps i use (Dash, for example, wouldn't be able to use only shift+h as shortcut, as it's not a system-wise allowed shortcut, hence the cmd+shift+h).

thanks!

**Comment by nbelzer** [comment]
Hey there, under the hood we use [mousetrap](https://craig.is/killing/mice) which specifies the command key as simply that `command`. So you would use `command+shift+h` and `command+shift+l` to go back and forward. I tested both of these locally and they work fine!

I'll consider this issue closed, let me know if you need any further help.

**Comment by godbout** [comment]
ok, not sure how i missed that one lol. maybe i found it actually but it might have caused issue with getting to homepage/reading list when you're already at the top/bottom of the stack. anyways, i ended up going through mapping Keyboard Shortcuts through macOS to get every app to behave the same. thanks!
