### ISSUE TITLE
Custom userSettings not working

### ISSUE THREAD

**Issue by srikat** [televator-apps/vimari#231]
I want to use `c` for closing the tab and not the default `x`.

So in the config file, changed

```
"closeTab": "x",
```

to

```
"closeTab": "c",
```

Saved userSettings.json and restarted Safari.

But pressing `x` continues to close the tab and not `c`.

Here's my full config:

Any idea?

```
{
  "excludedUrls": "^https?\:\/\/.*\?ct_builder=true.*",
  "linkHintCharacters": "asdfjklqwerzxc",
  "detectByCursorStyle": false,
  "scrollSize": 150,
  "openTabUrl": "https://duckduckgo.com/",
  "modifier": "",
  "smoothScroll": true,
  "scrollDuration": 25,
  "transparentBindings": true,
  "bindings": {
      "hintToggle": "f",
      "newTabHintToggle": "shift+f",
      "scrollUp": "k",
      "scrollDown": "j",
      "scrollLeft": "h",
      "scrollRight": "l",
      "scrollUpHalfPage": "u",
      "scrollDownHalfPage": "d",
      "goToPageTop": "g g",
      "goToPageBottom": "shift+g",
      "goToFirstInput": "g i",
      "goBack": "z",
      "goForward": "x",
      "reload": "r",
      "tabForward": "s",
      "tabBack": "a",
      "closeTab": "c",
      "openTab": "t"
  }
}
```

Do I need to add `unmap x` somewhere? If so, where/how?

**Comment by ybbond** [comment]
I once had similar problems to you (#227). I suggest to try clean reinstall Vimari (use AppCleaner to full uninstall, then redownload via AppStore).

**Comment by srikat** [comment]
Thanks for the suggestion. Just tried and didn't work. I will try again this time quitting Safari, uninstalling using AppCleaner and re-installing from the AppStore.

**Comment by srikat** [comment]
I have narrowed down the problem to

```
"excludedUrls": "^https?\:\/\/.*\?ct_builder=true.*",
```

specifically, the value of `^https?\:\/\/.*\?ct_builder=true.*` was breaking it.

Changed it to `ct_builder=true` and all good.
