### ISSUE TITLE
What is the syntax of the excludedUrls should be clearer

### ISSUE THREAD

**Issue by richtong** [televator-apps/vimari#234]
**Is your feature request related to a problem? Please describe.**
You have an excludedURLs field but it is not obvious what syntax you are using to specify this. Is it straight string search or are yousing a regex

**Describe the solution you'd like**
I have a bunch of urls like localhost:8888, 127.0.0.1:8888, deepnote which are all places that have keyboard shortcuts for Jupyter notebooks and Vimari overloads these. 

I only see examples like "excludedURLs": "github.com" but how can you specifiy this, does the excludedURLs take a JSON array or does it take a regex and if so what is the library being used.

**Describe alternatives you've considered**
Manually turning on and off Vimari on sites liek this. Ugh!

**Additional context**
It's a bit of documentation and I'm happy to issue a PR once you explain it :-)

**Comment by eudinaesis** [comment]
I agree, it would be helpful to have more info. Here's what I learned from looking at the function in injected.js -- code here:

```
    excludedUrls = storedExcludedUrls.split(",");
    for (_i = 0, _len = excludedUrls.length; _i < _len; _i++) {
        url = excludedUrls[_i];
        formattedUrl = stripProtocolAndWww(url);
        formattedUrl = formattedUrl.toLowerCase().trim();
        regexp = new RegExp('((.*)?(' + formattedUrl + ')+(.*))');
        if (currentUrl.toLowerCase().match(regexp)) {
            return true;
        }
    }
```

Vimari wants a single string, with commas (and possible whitespace) separating URLs. For example:

`"excludedUrls": "mail.google.com, earth.google.com, meet.google.com",`

 A JSON array would make more sense, but okay. It splits the string on commas to make an array, and for each URL:
- removes protocols & www
- lowercases
- trims whitespace
- creates a regex: (possible other characters) + url + (possible other characters)
- and matches the actual URL (lowercased) against this regex

**Comment by psifertex** [comment]
Related (and I'm happy to file a separate bug if that's preferred): if the format is invalid the feature silently stops working, no warning about a malformed file at all. I was missing a comma at the end of my configuration file and there was zero feedback anywhere that I could tell that it was broken. I came to this bug trying to figure out what the exact formatting was because I wasn't sure what the proper syntax was.

**Comment by richtong** [comment]
yes this is super confusing, not very json-like is the problem, I was thinking it wanted an array of strings like

"excludedURLs" : [ "url.com", "url2.com"],

But thanks for this!
