### ISSUE TITLE
Not available on US App Store

### ISSUE THREAD

**Issue by lukepighetti** [televator-apps/vimari#277]
<img width="299" alt="Screen Shot 2022-10-12 at 9 50 22 AM" src="https://user-images.githubusercontent.com/666539/195360799-e4b98d8a-5518-4388-935f-961ed987fcb3.png">

**Comment by manuelhubacher** [comment]
The same in the Swiss App Store 

![SCR-20221015-ou3](https://user-images.githubusercontent.com/17408325/195995908-b98c11ac-328f-42a3-8c0e-2173d8f2a926.jpeg)

**Comment by vladdoster** [comment]
@manuelhubacher, @lukepighetti

Given the lack of activity in the repository, I'd assume the author's Apple development account subscription expired and they declined/forgot to renew it.

See here for [Apple Developer Program cost](https://developer.apple.com/support/compare-memberships/).

**Comment by vladdoster** [comment]
I went ahead and made Vimari a Homebrew cask (see [vladdoster/vimari-homebrew-cask](https://github.com/vladdoster/vimari-homebrew-cask)).

Vimari failed to meet [Homebrew project standards](https://github.com/Homebrew/homebrew-cask/pull/133606) so now I host a tap for Vimari.

To install Vimari, run: 

```bash
brew install --cask vladdoster/formulae/vimari
```

Output:

```console
ᐳ brew install --cask vladdoster/formulae/vimari 
==> Tapping vladdoster/formulae
Cloning into '/opt/homebrew/Library/Taps/vladdoster/homebrew-formulae'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 10 (delta 1), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (10/10), done.
Resolving deltas: 100% (1/1), done.
Tapped 1 cask (14 files, 10.8KB).
==> Downloading https://github.com/televator-apps/vimari/releases/download/v2.1.0/Vimari.app.zip
Already downloaded: /Users/anonymous/Library/Caches/Homebrew/downloads/70cb93c2f1ff06455582c8a46d40e9a677c96080bfda993defccc46e47813ed2--Vimari.app.zip
==> Installing Cask vimari
==> Moving App 'Vimari.app' to '/Applications/Vimari.app'
🍺  vimari was successfully installed!
```

**Comment by lukepighetti** [comment]
Thank you!

**Comment by danielcompton** [comment]
Hi folks, sorry about this, my developer membership expired. I've renewed it now and you should see it available on the App Store soon.

**Comment by lgessl** [comment]
Could it be that your developer membership expired again (after pretty exactly 3 years)? I can't find Vimari any more in the German App Store:

<img width="1499" height="630" alt="Image" src="https://github.com/user-attachments/assets/017c66d1-8e01-41a8-befa-d6b4bf04b3c8" />

**Comment by vladdoster** [comment]
> Could it be that your developer membership expired again (after pretty exactly 3 years)? I can't find Vimari any more in the German App Store:
> 
> <img alt="Image" width="1499" height="630" src="https://private-user-images.githubusercontent.com/96291220/502980329-017c66d1-8e01-41a8-befa-d6b4bf04b3c8.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQxODkzNjgsIm5iZiI6MTc2NDE4OTA2OCwicGF0aCI6Ii85NjI5MTIyMC81MDI5ODAzMjktMDE3YzY2ZDEtOGUwMS00MWE4LWJlZmEtZDZiNGJmMDRiM2M4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTI2VDIwMzEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZjEzYjViYzgzMTViYjFhNGI2YTdhMDQwYjI4NGI5NTM0NjQxYzgzMmRhYWZjNmQzZmU0YTg0MGRiZTcyODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g2zHZ0rw2fQnqWjUX5k9_qhRpmX7-nyKqZu1toOp5ok">

@lgessl, correct. See this [alternative install method](https://github.com/televator-apps/vimari/issues/277#issuecomment-1279825198).
