### ISSUE TITLE
app is not in India market

### ISSUE THREAD

**Issue by antonyr** [televator-apps/vimari#292]
Vimari is not available in India app store.

**Comment by rdewolff** [comment]
same for Switzerland. Cannot download the app

![CleanShot 2023-11-20 at 08 07 30](https://github.com/televator-apps/vimari/assets/130704/e4680fab-f129-4173-aef9-fcdad0dc2693)

**Comment by HakimiX** [comment]
It's also no longer available in Denmark

**Comment by danielcompton** [comment]
Sorry about that, it should be available now. It might take up to 24 hours for it to be available in the App Store.

**Comment by antonyr** [comment]
Thanks @danielcompton for making it available for us.
