### ISSUE TITLE
support smoother scroll?

### ISSUE THREAD

**Issue by xudshen** [televator-apps/vimari#44]

**Comment by horak** [comment]
Just dropping here that I agree with @xudshen, I find it easier to read content with a bit of movement.

**Comment by icecreammatt** [comment]
I have to say that I really enjoy the smooth scrolling that VimFX has in Firefox. Maybe it could be an option for Safari. I find I'm less likely to lose my place in a page when it is enabled.

**Comment by x3qt** [comment]
I am fully agree with @icecreammatt on losing my place without smooth transition.

**Comment by Wyc0** [comment]
I've got the same opinion as people above : ). Just like vimium in chrome

**Comment by xaviervalarino** [comment]
Vimari is using `window.scrollBy`, which is specified in the [*CCSOM View Module*](https://drafts.csswg.org/cssom-view/#scrolling) to have `behavior: 'smooth'` as an option, (but as of writing, has only been implemented in Firefox).

There is a polyfill for this behavior:
* http://iamdustan.com/smoothscroll/
* https://github.com/iamdustan/smoothscroll

@guyht: would you accept a PR that offered smooth-scroll as an option using this polyfill?

**Comment by jacobchrismarsh** [comment]
The `windows.scrollBy` function in safari does not support the `'smooth'` option
