### ISSUE TITLE
Enhancement: fade shortcuts on Link Hinting

### ISSUE THREAD

**Issue by evertonfraga** [televator-apps/vimari#79]
Scenario: After I press Ctrl+F, a page that has lots of links will display a bunch of labels with letters such as: LK, SK, LL, SJ.

If I press S at first, only SK and SJ will have its 'S' fade out. As an enhancement, would be nicer if LK and LL would also fade in this sort of situations.

I just moved from Chrome + Vimium, and thanks for the Vimari extension.

**Comment by danielcompton** [comment]
Adding to the above feature request, in Vimium on Chrome, it removes any non-matching link hints completely. This makes it easier to navigate and to see the page underneath all the link hints.

<img width="2547" alt="Screen Shot 2019-04-10 at 1 58 03 PM" src="https://user-images.githubusercontent.com/811954/55846158-b6b54380-5b98-11e9-94e9-78963559d03f.png">

After typing one character:

<img width="2547" alt="Screen Shot 2019-04-10 at 1 58 11 PM" src="https://user-images.githubusercontent.com/811954/55846152-b026cc00-5b98-11e9-8fd7-2bb14295af58.png">

**Comment by evertonfraga** [comment]
Awesome :)
