### ISSUE TITLE
How to focus the first text input on the page?

### ISSUE THREAD

**Issue by livc** [televator-apps/vimari#88]

**Comment by simeg** [comment]
Could you explain your use case a bit more? The question in the title I'd just respond to with: Use `Ctrl + F` and select the input field, but I'm guessing it's not working for you?

**Comment by livc** [comment]
Can you refer to [vimium for chrome](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en?) the shortcut `gi` in vimium is to focus the first text input on the page.

In Google search result page, this feature can help make the cursor focus on Google search box on the top of the result page.

**Comment by jgogstad** [comment]
+1. This is definitely the number one feature I use in vimperator (for Firefox)

**Comment by dioxide** [comment]
+1 .  most usefully feature.   please refer to chrome's plugin(named surfingkeys),  the shortcut is "**i**".

**Comment by isundaylee** [comment]
I implemented this a while back in PR #133. I can rebase and resolve the merge conflicts if there is interest from the maintainer for merging it.

**Comment by rk1** [comment]
@livc Seems like since #133 is merged this can be closed, `gi` is working as expected for me in the latest release.
